import { hash } from "bcryptjs";
import { getPrismaClient } from "@/lib/prisma";
import defaultConfig from "@/lib/config/defaultConfig";

const DEMO_USER_EMAIL = "demo@example.com";
const DEMO_USER_PASSWORD = "demo12345";

function buildSampleGenericRecord(entityName: string, index: number) {
  return {
    name: `${entityName} ${index + 1}`,
    title: `${entityName} Item ${index + 1}`,
    status: index % 2 === 0 ? "active" : "draft",
    notes: `Autogenerated sample data for ${entityName}.`,
  };
}

async function main() {
  const prisma = getPrismaClient();
  await prisma.appConfigState.upsert({
    where: { key: "current" },
    update: { value: defaultConfig as never },
    create: { key: "current", value: defaultConfig as never },
  });

  const hashedPassword = await hash(DEMO_USER_PASSWORD, 10);

  const demoUser = await prisma.user.upsert({
    where: { email: DEMO_USER_EMAIL },
    update: {
      password: hashedPassword,
    },
    create: {
      email: DEMO_USER_EMAIL,
      password: hashedPassword,
    },
  });

  const leads = [
    {
      name: "Ada Lovelace",
      email: "ada@example.com",
      company: "Analytical Engines Ltd.",
      status: "new",
      estimatedValue: 12000,
    },
    {
      id: "665000000000000000000102",
      name: "Grace Hopper",
      email: "grace@example.com",
      company: "Compiler Co.",
      status: "contacted",
      estimatedValue: 28000,
    },
    {
      id: "665000000000000000000103",
      name: "Katherine Johnson",
      email: "katherine@example.com",
      company: "Orbital Systems",
      status: "qualified",
      estimatedValue: 42000,
    },
  ];

  const tasks = [
    {
      title: "Follow up with Ada",
      dueDate: "2026-05-04",
      priority: "high",
      status: "todo",
      notes: "Send pricing and implementation timeline.",
    },
    {
      title: "Prepare Grace demo",
      dueDate: "2026-05-06",
      priority: "medium",
      status: "in_progress",
      notes: "Focus on import workflow and reporting.",
    },
    {
      title: "Send Katherine proposal",
      dueDate: "2026-05-09",
      priority: "high",
      status: "todo",
      notes: "Include onboarding plan and success metrics.",
    },
  ];

  await prisma.entityRecord.deleteMany({
    where: { userId: demoUser.id },
  });

  for (const lead of leads) {
    await prisma.entityRecord.create({
      data: {
        userId: demoUser.id,
        entityType: "Lead",
        recordData: lead as never,
      },
    });
  }

  for (const task of tasks) {
    await prisma.entityRecord.create({
      data: {
        userId: demoUser.id,
        entityType: "Task",
        recordData: task as never,
      },
    });
  }

  const extraEntities = (defaultConfig.entities ?? []).filter((entity) => !["Lead", "Task"].includes(entity.name ?? ""));

  for (const entity of extraEntities) {
    const entityName = entity.name ?? entity.label ?? "Entity";

    for (let index = 0; index < 3; index += 1) {
      await prisma.entityRecord.create({
        data: {
          userId: demoUser.id,
          entityType: entityName,
          recordData: buildSampleGenericRecord(entityName, index) as never,
        },
      });
    }
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
